platform: 10.11.92.33

workspace:
  base: /go
  path: src/github.com/operator-framework/operator-sdk

clone:
  git:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    dns: 223.5.5.5
    when:
      branch:
        - dev

pipeline:
  helm-golang:
    image: registry.cn-qingdao.aliyuncs.com/wod/golang:1.16.5-alpine
    dns: 223.5.5.5
    volumes:
      - /data/cache/golang/mod:/go/pkg/mod
    environment:
      - GOPROXY=https://goproxy.cn
    commands:
      - git apply .beagle/20210605-helm-fix.patch
      - sh .beagle/build.sh
    when:
      branch:
        - dev

  helm-docker:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.13
    dockerfile: .beagle/helm-operator/Dockerfile
    repo: wod/helm-operator
    version: 'v1.8.0'
    channel: alpha
    args: 'TARGETOS=linux,TARGETARCH=amd64'
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - dev

  helm-harbor:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/helm-operator:v1.8.0-alpha
    target: registry.cn-qingdao.aliyuncs.com/wod/helm-operator:v1.8.0
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master

  helm-docker-arm64:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.13-arm64
    dockerfile: .beagle/helm-operator/Dockerfile
    repo: wod/helm-operator
    version: 'v1.8.0'
    channel: 'alpha-arm64'
    args: 'TARGETOS=linux,TARGETARCH=arm64'
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - dev

  helm-harbor-arm64:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/helm-operator:v1.8.0-alpha-arm64
    target: registry.cn-qingdao.aliyuncs.com/wod/helm-operator:v1.8.0-arm64
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master

  helm-docker-ppc64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.13-ppc64le
    dockerfile: .beagle/helm-operator/Dockerfile
    repo: wod/helm-operator
    version: 'v1.8.0'
    channel: 'alpha-ppc64le'
    args: 'TARGETOS=linux,TARGETARCH=ppc64le'
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - dev

  helm-harbor-ppc64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/helm-operator:v1.8.0-alpha-ppc64le
    target: registry.cn-qingdao.aliyuncs.com/wod/helm-operator:v1.8.0-ppc64le
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master
