apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://kubernetes.home.wodcloud.local
    insecure-skip-tls-verify: true
users:
- name: local
  user:
    token: 7176d48e4e66ddb3557a82f2dd316a93
contexts:
- context:
    cluster: local
    user: local
  name: local
current-context: local